force-app/batch-panel/objects/Batch_Detail__c/Batch_Detail__c.object-meta.xml
<CustomObject>
    <label>Batch Detail</label>
    <nameField>
        <label>Batch Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/batch-panel/objects/Batch_Detail__c/fields/Interval_Mode__c.field-meta.xml
<CustomField>
    <fullName>Interval_Mode__c</fullName>
    <label>Interval Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Minutes</fullName>
                <default>true</default>
                <label>Minutes</label>
            </value>
            <value>
                <fullName>Hours</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/batch-panel/objects/Batch_Detail__c/fields/Panel_Label__c.field-meta.xml
<CustomField>
    <fullName>Panel_Label__c</fullName>
    <label>Panel Label</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/batch-panel/objects/Batch_Detail__c/fields/Relaunch_Interval__c.field-meta.xml
<CustomField>
    <fullName>Relaunch_Interval__c</fullName>
    <label>Relaunch Interval</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/batch-panel/objects/Batch_Detail__c/fields/Scope_Size__c.field-meta.xml
<CustomField>
    <fullName>Scope_Size__c</fullName>
    <label>Scope Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/batch-panel/tests/Test_BatchScheduledAbstract.cls
/**
 * Created by Igor Malyuta on 04.08.2021.
 */
@IsTest
public with sharing class Test_BatchScheduledAbstract {

    @TestSetup
    static void setup() {
        insert new Batch_Detail__c(
                Name = 'Test_BatchScheduledAbstract.Batch_ForTest',
                Interval_Mode__c = Batch_ScheduledAbstract.INTERVAL_MINUTES,
                Panel_Label__c = 'Test_BatchScheduledAbstract.Batch_ForTest',
                Relaunch_Interval__c = 1,
                Scope_Size__c = 200
        );
    }

    @IsTest
    static void abstractClassTest() {
        Batch_ScheduledAbstract batchForTest = new Batch_ForTest();
        System.assertEquals(Batch_ForTest.class, batchForTest.getType());
        System.assertEquals(null, batchForTest.getBatchDescription());
        System.assertEquals(Batch_ScheduledAbstract.INTERVAL_MINUTES, batchForTest.getRecommendedIntervalMode());
        System.assertEquals(10, batchForTest.getRecommendedRelaunchInterval());
        System.assertEquals(200, batchForTest.getRecommendedScopeSize());
        batchForTest.finish(null);
    }

    public class Batch_ForTest extends Batch_ScheduledAbstract {

        public Database.QueryLocator start(Database.BatchableContext param1) {
            return Database.getQueryLocator('SELECT Id FROM Account');
        }

        public void execute(Database.BatchableContext bc, List<Object> accounts) {
            //Some logic here
        }

        public override Type getType() {
            return Batch_ForTest.class;
        }

        public override void finalAction() {
            System.debug('Some action...');
        }
    }
}